name: safe_upgrade
description: Safe Upgrade Windows Installer By Schrock Innovations.


version: 2.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  auto_updater: ^0.1.7
  bitsdojo_window: ^0.1.5
  desktop_window: ^0.4.0
  device_info_plus: ^8.2.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_login: ^4.2.1
  package_info_plus: ^3.1.2
  launch_at_startup: ^0.2.2
  lottie: ^2.6.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  process_run: ^0.13.1
  universal_disk_space: ^0.2.3
  msix: ^3.16.4
  windows_single_instance: ^1.0.0
  dio: ^5.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
   - assets/images/appBarBg.png
   - assets/images/schrockInnovationsLogo.png
   - assets/lottie/loading.json
   - assets/lottie/transactionFailed.json
   - assets/lottie/success2.json
   - assets/lottie/downloading-animation.json
   - assets/lottie/making-notes.json
   - assets/lottie/question-animation.json


#msix_config:
#  display_name: Safe Upgrade 23h2
#  publisher_display_name: Schrock Innovations Inc.
#  identity_name: company.suite.flutterapp
#  msix_version: 1.0.0.0
#  logo_path: C:\Users\code signer\Desktop\Schrock-Innovations-Glossy-RGB-1.png
#  capabilities: internetClient, location, microphone, webcam

msix_config:
  display_name: Safe Upgrade 23H2
  publisher_display_name: Schrock Innovations, Inc
  #  publisher: Schrock Innovations, Inc
  identity_name: Safe-Upgrade-23H2
  msix_version: 1.0.0.1
  languages: en-us
  capabilities: "internetClient"
  signtool_options: /fd SHA256 /f "C:\Users\Alfonso\StudioProjects\sophosFlutter\certificates\schrockInnovations3.pfx" /p Vcuz3kgOnEQYlL1A

  logo_path: C:\Users\code signer\Desktop\Schrock-Innovations-Glossy-RGB-1.png

  certificate_path: C:\Users\Alfonso\StudioProjects\sophosFlutter\certificates\schrockInnovations3.pfx
  certificate_password: Vcuz3kgOnEQYlL1A