name: safe_upgrade
description: Safe Upgrade Windows Installer By Schrock Innovations.


version: 2.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  auto_updater: ^0.1.7
  bitsdojo_window: ^0.1.5
  desktop_window: ^0.4.0
  device_info_plus: ^8.2.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_login: ^4.2.1
  package_info_plus: ^3.1.2
  launch_at_startup: ^0.2.2
  lottie: ^2.6.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  process_run: ^0.13.1
  universal_disk_space: ^0.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
   - assets/images/appBarBg.png
   - assets/images/schrockInnovationsLogo.png
   - assets/lottie/loading.json
   - assets/lottie/transactionFailed.json
   - assets/lottie/success2.json
   - assets/lottie/downloading-animation.json
   - assets/lottie/making-notes.json
   - assets/lottie/question-animation.json


